name = "pwxavengers-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Enable logging
logpush = true

[env.production]
name = "pwxavengers-proxy"
logpush = true

[env.staging]
name = "pwxavengers-proxy-staging"
logpush = true

# Routes configuration - uncomment and modify as needed
# routes = [
#   { pattern = "your-domain.com/api/*", zone_name = "your-domain.com" }
# ]

# Custom domain configuration - uncomment and modify as needed
# [[env.production.routes]]
# pattern = "api.your-domain.com/*"
# zone_name = "your-domain.com"
